/**
 * Nội dung các trang policy (legal) của Home — localized, type-safe, **thuộc
 * sở hữu của application**.
 *
 * Cùng nguyên tắc với `HOME_CONTENT`: app tự sở hữu content của mình,
 * `layout-public` chỉ sở hữu chrome dùng chung và không biết content của app.
 * Cấu trúc `Record<PublicLocale, …>` khiến thêm một locale mà thiếu bản dịch
 * là lỗi type ngay tại khai báo.
 *
 * Đây là **bản nháp trung tính**: mô tả đúng các nguyên tắc vận hành chung,
 * không bịa số liệu kinh doanh cụ thể (mức giá, SLA, thời hạn hoàn tiền…) —
 * phần đó thuộc sở hữu business/pháp lý và phải được review trước khi public
 * hoá bất kỳ cam kết nào. Mọi câu đều viết ở mức policy statement, không hứa
 * hẹn tính năng chưa có.
 */

import type { PublicLocale } from '@ecoma-io/i18n-public';

/**
 * Một đề mục trong nội dung policy: heading + các đoạn văn.
 *
 * `readonly` ở mọi field: content là dữ liệu tĩnh, không phải mutable state.
 * Thuần dữ liệu (không hàm, không VNode) nên render như nhau ở server và
 * client — cùng input cho cùng output.
 */
export type LegalSection = {
  /** Tiêu đề đề mục (`<h2>`). */
  readonly heading: string;
  /** Các đoạn văn của đề mục, theo thứ tự hiển thị. */
  readonly paragraphs: readonly string[];
};

/** Nội dung một trang policy cho một locale. */
export type LegalPageContent = {
  /** Tiêu đề tài liệu (localized) — `document.title`. */
  readonly title: string;
  /** Tiêu đề chính của trang (một `<h1>` duy nhất). */
  readonly heading: string;
  /** Mô tả ngắn một câu, dùng cho meta description. */
  readonly description: string;
  /** Các đề mục nội dung, theo thứ tự hiển thị. */
  readonly sections: readonly LegalSection[];
};

/**
 * Slug của năm trang policy — dữ liệu duy nhất khai báo tập trang legal tồn
 * tại. Route của app validate theo chính tập này; slug ngoài tập là 404.
 *
 * Slug là định danh URL, giữ nguyên ở cả hai locale (không dịch URL).
 */
export const LEGAL_SLUGS = Object.freeze([
  'privacy',
  'terms',
  'service-delivery',
  'payment',
  'refund',
] as const);

export type LegalSlug = (typeof LEGAL_SLUGS)[number];

/**
 * Nội dung policy cho mọi locale của registry — khoá ngoài là
 * `Record<PublicLocale, …>`, khoá trong là `Record<LegalSlug, …>`; thiếu bản
 * dịch hay thiếu trang là lỗi compile time, không có fallback runtime.
 */
export const LEGAL_CONTENT: Readonly<
  Record<PublicLocale, Readonly<Record<LegalSlug, LegalPageContent>>>
> = Object.freeze({
  en: Object.freeze({
    privacy: Object.freeze({
      title: 'Privacy Policy — ecoma.io',
      heading: 'Privacy Policy',
      description: 'How ecoma.io collects, uses and protects personal data.',
      sections: Object.freeze([
        {
          heading: 'Overview',
          paragraphs: Object.freeze([
            'This policy explains what personal data ecoma.io collects when you use its public website and services, why that data is processed, and the choices available to you.',
            'We collect only the data that is needed to operate, secure and improve the service, and we do not sell personal data.',
          ]),
        },
        {
          heading: 'Data we collect',
          paragraphs: Object.freeze([
            'Account data: identifiers you provide when you register or contact us, such as your name, email address and organisation.',
            'Usage data: technical records generated by your interaction with the site, such as requested pages, response status and coarse device characteristics. This data is used in aggregate form for capacity and reliability work.',
          ]),
        },
        {
          heading: 'How data is used',
          paragraphs: Object.freeze([
            'To deliver the service you requested, to authenticate you, to prevent abuse, and to communicate service-related announcements.',
            'To measure aggregate usage so we can understand which surfaces are useful and keep them reliable.',
          ]),
        },
        {
          heading: 'Sharing and processing',
          paragraphs: Object.freeze([
            'Personal data is processed by ecoma.io and, where strictly necessary, by service providers acting on our behalf under contract. Each provider is limited to the data required for its function.',
            'We may disclose data when required by applicable law, and only to the extent required.',
          ]),
        },
        {
          heading: 'Retention and your rights',
          paragraphs: Object.freeze([
            'Personal data is kept only as long as needed for the purposes described above, after which it is deleted or de-identified.',
            'You may request access to, correction of, or deletion of your personal data by contacting us. We respond to verified requests within the timeframe required by applicable law.',
          ]),
        },
        {
          heading: 'Changes to this policy',
          paragraphs: Object.freeze([
            'When this policy changes materially, we publish the updated version on this page and, where appropriate, announce the change through the service before it takes effect.',
          ]),
        },
      ]),
    }),
    terms: Object.freeze({
      title: 'Terms of Service — ecoma.io',
      heading: 'Terms of Service',
      description: 'The terms that govern your use of ecoma.io services.',
      sections: Object.freeze([
        {
          heading: 'Acceptance',
          paragraphs: Object.freeze([
            'By accessing or using ecoma.io you agree to these terms. If you use the service on behalf of an organisation, you represent that you are authorised to bind that organisation.',
          ]),
        },
        {
          heading: 'The service',
          paragraphs: Object.freeze([
            'ecoma.io provides a software platform together with its public website, documentation and blog. The scope of the paid offering is described on the service surface where you subscribe.',
            'We may improve, change or discontinue individual features over time; where a change materially reduces a paid capability you rely on, we will give reasonable notice.',
          ]),
        },
        {
          heading: 'Acceptable use',
          paragraphs: Object.freeze([
            'You must not use the service to violate applicable law, to infringe the rights of others, to transmit malware, or to attempt to gain unauthorised access to any system or to data that is not yours.',
            'You must not interfere with the availability of the service for other users, including by generating load that a reasonable user would regard as abusive.',
          ]),
        },
        {
          heading: 'Accounts',
          paragraphs: Object.freeze([
            'You are responsible for the confidentiality of your credentials and for activity carried out through your account. Notify us promptly if you believe an account has been compromised.',
          ]),
        },
        {
          heading: 'Intellectual property',
          paragraphs: Object.freeze([
            'The service, including its software, text and design, is protected by intellectual property rights. You retain the rights to the content you process through the service.',
          ]),
        },
        {
          heading: 'Disclaimers and liability',
          paragraphs: Object.freeze([
            'The service is provided on an "as is" and "as available" basis to the extent permitted by law. Nothing in these terms excludes liability that cannot be excluded under applicable law.',
          ]),
        },
      ]),
    }),
    'service-delivery': Object.freeze({
      title: 'Service Delivery Policy — ecoma.io',
      heading: 'Service Delivery Policy',
      description: 'How ecoma.io delivers, operates and supports its services.',
      sections: Object.freeze([
        {
          heading: 'Scope',
          paragraphs: Object.freeze([
            'This policy describes how ecoma.io delivers the services you subscribe to: where they run, how they are maintained, and how operational incidents are handled.',
          ]),
        },
        {
          heading: 'Delivery model',
          paragraphs: Object.freeze([
            'The service is delivered as a hosted platform served from regional edge infrastructure. You do not need to install or maintain server software to use it.',
            'The public website and documentation are served under a locale prefix, so every URL names the language it renders in.',
          ]),
        },
        {
          heading: 'Maintenance and changes',
          paragraphs: Object.freeze([
            'Routine maintenance is performed without service interruption wherever the platform allows it. When a maintenance window cannot be avoided, it is scheduled and announced in advance.',
          ]),
        },
        {
          heading: 'Incidents and status',
          paragraphs: Object.freeze([
            'Operational incidents are triaged as they are detected. We work to restore service first, then to publish an explanation of the cause and the fix for significant incidents.',
          ]),
        },
        {
          heading: 'Support',
          paragraphs: Object.freeze([
            'Support is provided through the channels published on the service surface you use. Response expectations depend on your subscription tier and the severity of the issue.',
          ]),
        },
      ]),
    }),
    payment: Object.freeze({
      title: 'Payment Policy — ecoma.io',
      heading: 'Payment Policy',
      description: 'How subscriptions and invoices are billed and settled at ecoma.io.',
      sections: Object.freeze([
        {
          heading: 'Scope',
          paragraphs: Object.freeze([
            'This policy describes how paid services are billed, which payment methods are accepted, and how billing disputes are handled.',
          ]),
        },
        {
          heading: 'Billing model',
          paragraphs: Object.freeze([
            'Paid services are billed in advance for each subscription period, at the price displayed on the service surface at the time of purchase. Where usage-based charges apply, they are metered and billed according to the terms shown at purchase.',
            'Applicable taxes are calculated and shown before you confirm a payment.',
          ]),
        },
        {
          heading: 'Payment methods',
          paragraphs: Object.freeze([
            "Payments are processed by our payment provider. Payment card data is entered directly into the provider's form and is never stored on ecoma.io systems.",
          ]),
        },
        {
          heading: 'Failed payments and suspension',
          paragraphs: Object.freeze([
            'If a payment cannot be collected, we notify you and retry within a reasonable window. A subscription may be suspended if payment remains unsuccessful after that window; data is retained in accordance with the applicable retention policy.',
          ]),
        },
        {
          heading: 'Billing disputes',
          paragraphs: Object.freeze([
            'If you believe an invoice is incorrect, contact us before the due date with the invoice reference and the reason for the dispute. We investigate and correct confirmed errors on the next invoice or by refund, as appropriate.',
          ]),
        },
      ]),
    }),
    refund: Object.freeze({
      title: 'Refund Policy — ecoma.io',
      heading: 'Refund Policy',
      description: 'When and how ecoma.io issues refunds.',
      sections: Object.freeze([
        {
          heading: 'Scope',
          paragraphs: Object.freeze([
            'This policy describes when a refund can be requested, how requests are assessed, and how approved refunds are returned.',
          ]),
        },
        {
          heading: 'Eligibility',
          paragraphs: Object.freeze([
            'Where the law of your jurisdiction grants a withdrawal or refund right that is wider than this policy, that law prevails.',
            'A refund may be requested when a paid capability was unavailable to you in a way that was caused by ecoma.io and not remedied within a reasonable time, or when an invoice was issued in error.',
          ]),
        },
        {
          heading: 'How to request',
          paragraphs: Object.freeze([
            'Requests are made through the support channel published on the service surface, quoting the invoice or subscription reference and describing the issue. We confirm receipt and respond with the outcome.',
          ]),
        },
        {
          heading: 'Processing refunds',
          paragraphs: Object.freeze([
            'Approved refunds are returned through the original payment method. The time for the amount to appear depends on the payment provider and typically takes several business days.',
            'Where only part of a subscription period is affected, the refund is proportionate to the affected part unless the error was ours, in which case the affected amount is refunded in full.',
          ]),
        },
      ]),
    }),
  }),
  vi: Object.freeze({
    privacy: Object.freeze({
      title: 'Chính sách bảo mật — ecoma.io',
      heading: 'Chính sách bảo mật',
      description: 'Cách ecoma.io thu thập, sử dụng và bảo vệ dữ liệu cá nhân.',
      sections: Object.freeze([
        {
          heading: 'Tổng quan',
          paragraphs: Object.freeze([
            'Chính sách này giải thích dữ liệu cá nhân nào được ecoma.io thu thập khi bạn sử dụng website public và dịch vụ, dữ liệu đó được xử lý vì lý do gì, và bạn có những lựa chọn nào.',
            'Chúng tôi chỉ thu thập dữ liệu cần thiết để vận hành, bảo vệ và cải thiện dịch vụ, và không bán dữ liệu cá nhân.',
          ]),
        },
        {
          heading: 'Dữ liệu chúng tôi thu thập',
          paragraphs: Object.freeze([
            'Dữ liệu tài khoản: các định danh bạn cung cấp khi đăng ký hoặc liên hệ, chẳng hạn tên, địa chỉ email và tổ chức.',
            'Dữ liệu sử dụng: bản ghi kỹ thuật phát sinh khi bạn tương tác với trang, chẳng hạn trang được yêu cầu, trạng thái phản hồi và đặc điểm thiết bị ở mức tổng quát. Dữ liệu này được dùng ở dạng tổng hợp cho công việc dung lượng và độ tin cậy.',
          ]),
        },
        {
          heading: 'Cách dữ liệu được sử dụng',
          paragraphs: Object.freeze([
            'Để cung cấp dịch vụ bạn yêu cầu, xác thực bạn, phòng chống lạm dụng, và gửi thông báo liên quan đến dịch vụ.',
            'Để đo mức sử dụng tổng hợp nhằm hiểu bề mặt nào hữu ích và giữ chúng ổn định.',
          ]),
        },
        {
          heading: 'Chia sẻ và xử lý',
          paragraphs: Object.freeze([
            'Dữ liệu cá nhân được ecoma.io xử lý và, khi thật sự cần thiết, bởi các nhà cung cấp dịch vụ hoạt động thay mặt chúng tôi theo hợp đồng. Mỗi nhà cung cấp chỉ được dùng lượng dữ liệu tối thiểu cho chức năng của họ.',
            'Chúng tôi có thể công bố dữ liệu khi luật hiện hành yêu cầu, và chỉ ở mức độ được yêu cầu.',
          ]),
        },
        {
          heading: 'Lưu trữ và quyền của bạn',
          paragraphs: Object.freeze([
            'Dữ liệu cá nhân chỉ được giữ trong thời gian cần thiết cho các mục đích nêu trên, sau đó bị xoá hoặc vô danh hoá.',
            'Bạn có thể yêu cầu truy xuất, chỉnh sửa hoặc xoá dữ liệu cá nhân của mình bằng cách liên hệ chúng tôi. Chúng tôi trả lời các yêu cầu đã xác thực trong thời hạn theo luật hiện hành.',
          ]),
        },
        {
          heading: 'Thay đổi chính sách',
          paragraphs: Object.freeze([
            'Khi chính sách này thay đổi đáng kể, chúng tôi đăng phiên bản mới tại trang này và, khi phù hợp, thông báo thay đổi qua dịch vụ trước khi có hiệu lực.',
          ]),
        },
      ]),
    }),
    terms: Object.freeze({
      title: 'Điều khoản dịch vụ — ecoma.io',
      heading: 'Điều khoản dịch vụ',
      description: 'Các điều khoản chi phối việc sử dụng dịch vụ của ecoma.io.',
      sections: Object.freeze([
        {
          heading: 'Chấp nhận',
          paragraphs: Object.freeze([
            'Khi truy cập hoặc sử dụng ecoma.io, bạn đồng ý với các điều khoản này. Nếu bạn sử dụng dịch vụ thay mặt một tổ chức, bạn khẳng định được uỷ quyền ràng buộc tổ chức đó.',
          ]),
        },
        {
          heading: 'Dịch vụ',
          paragraphs: Object.freeze([
            'ecoma.io cung cấp một nền tảng phần mềm cùng website public, tài liệu và blog. Phạm vi của bản trả phí được mô tả trên bề mặt dịch vụ nơi bạn đăng ký.',
            'Chúng tôi có thể cải tiến, thay đổi hoặc ngừng từng tính năng theo thời gian; khi một thay đổi làm giảm đáng kể khả năng trả phí mà bạn đang dùng, chúng tôi sẽ báo trước hợp lý.',
          ]),
        },
        {
          heading: 'Sử dụng hợp lệ',
          paragraphs: Object.freeze([
            'Bạn không được dùng dịch vụ để vi phạm luật hiện hành, xâm phạm quyền của người khác, truyền phần mềm độc hại, hoặc tìm cách truy cập trái phép vào bất kỳ hệ thống hay dữ liệu nào không thuộc về bạn.',
            'Bạn không được cản trở tính khả dụng của dịch vụ đối với người dùng khác, kể cả bằng việc tạo tải mà một người dùng hợp lý sẽ xem là lạm dụng.',
          ]),
        },
        {
          heading: 'Tài khoản',
          paragraphs: Object.freeze([
            'Bạn chịu trách nhiệm bảo mật thông tin đăng nhập và cho hoạt động diễn ra qua tài khoản của mình. Hãy báo cho chúng tôi ngay nếu bạn cho rằng tài khoản đã bị xâm nhập.',
          ]),
        },
        {
          heading: 'Sở hữu trí tuệ',
          paragraphs: Object.freeze([
            'Dịch vụ, bao gồm phần mềm, văn bản và thiết kế, được bảo vệ bởi các quyền sở hữu trí tuệ. Bạn giữ toàn bộ quyền đối với nội dung bạn xử lý qua dịch vụ.',
          ]),
        },
        {
          heading: 'Miễn trừ và trách nhiệm',
          paragraphs: Object.freeze([
            'Trong phạm vi pháp luật cho phép, dịch vụ được cung cấp trên cơ sở "nguyên trạng" và "theo tính khả dụng hiện có". Không điều khoản nào ở đây loại trừ trách nhiệm mà pháp luật không cho loại trừ.',
          ]),
        },
      ]),
    }),
    'service-delivery': Object.freeze({
      title: 'Chính sách cung cấp dịch vụ — ecoma.io',
      heading: 'Chính sách cung cấp dịch vụ',
      description: 'Cách ecoma.io cung cấp, vận hành và hỗ trợ dịch vụ.',
      sections: Object.freeze([
        {
          heading: 'Phạm vi',
          paragraphs: Object.freeze([
            'Chính sách này mô tả cách ecoma.io cung cấp dịch vụ bạn đăng ký: dịch vụ chạy ở đâu, được bảo trì thế nào, và sự cố vận hành được xử lý ra sao.',
          ]),
        },
        {
          heading: 'Mô hình cung cấp',
          paragraphs: Object.freeze([
            'Dịch vụ được cung cấp dưới dạng nền tảng hosted, phục vụ từ hạ tầng edge theo vùng. Bạn không cần cài đặt hay duy trì phần mềm server để sử dụng.',
            'Website public và tài liệu được phục vụ dưới một locale prefix, nên mọi URL luôn nêu rõ ngôn ngữ mà nó hiển thị.',
          ]),
        },
        {
          heading: 'Bảo trì và thay đổi',
          paragraphs: Object.freeze([
            'Bảo trì định kỳ được thực hiện không làm gián đoạn dịch vụ ở mức nền tảng cho phép. Khi bắt buộc có cửa sổ bảo trì, nó được lên lịch và thông báo trước.',
          ]),
        },
        {
          heading: 'Sự cố và trạng thái',
          paragraphs: Object.freeze([
            'Sự cố vận hành được phân loại ngay khi phát hiện. Chúng tôi ưu tiên khôi phục dịch vụ trước, sau đó công bố nguyên nhân và cách khắc phục đối với các sự cố đáng kể.',
          ]),
        },
        {
          heading: 'Hỗ trợ',
          paragraphs: Object.freeze([
            'Hỗ trợ được cung cấp qua các kênh được công bố trên bề mặt dịch vụ bạn dùng. Kỳ vọng thời gian phản hồi phụ thuộc gói đăng ký và mức độ nghiêm trọng của vấn đề.',
          ]),
        },
      ]),
    }),
    payment: Object.freeze({
      title: 'Chính sách thanh toán — ecoma.io',
      heading: 'Chính sách thanh toán',
      description: 'Cách các gói đăng ký và hoá đơn được tính phí và tất toán tại ecoma.io.',
      sections: Object.freeze([
        {
          heading: 'Phạm vi',
          paragraphs: Object.freeze([
            'Chính sách này mô tả cách dịch vụ trả phí được tính phí, các phương thức thanh toán được chấp nhận, và cách tranh chấp thanh toán được xử lý.',
          ]),
        },
        {
          heading: 'Mô hình tính phí',
          paragraphs: Object.freeze([
            'Dịch vụ trả phí được tính trước cho từng kỳ đăng ký, theo giá hiển thị trên bề mặt dịch vụ tại thời điểm mua. Ở nơi có phí theo mức sử dụng, mức dùng được đo và tính theo điều khoản hiển thị khi mua.',
            'Thuế áp dụng được tính và hiển thị trước khi bạn xác nhận thanh toán.',
          ]),
        },
        {
          heading: 'Phương thức thanh toán',
          paragraphs: Object.freeze([
            'Thanh toán được xử lý bởi nhà cung cấp thanh toán của chúng tôi. Dữ liệu thẻ được nhập trực tiếp vào biểu mẫu của nhà cung cấp và không bao giờ được lưu trên hệ thống của ecoma.io.',
          ]),
        },
        {
          heading: 'Thanh toán thất bại và tạm ngừng',
          paragraphs: Object.freeze([
            'Nếu khoản thanh toán không thu được, chúng tôi thông báo cho bạn và thử lại trong một khoảng thời gian hợp lý. Gói đăng ký có thể bị tạm ngừng nếu thanh toán vẫn không thành công sau khoảng đó; dữ liệu được giữ theo chính sách lưu trữ áp dụng.',
          ]),
        },
        {
          heading: 'Tranh chấp thanh toán',
          paragraphs: Object.freeze([
            'Nếu bạn cho rằng một hoá đơn không chính xác, hãy liên hệ trước hạn thanh toán kèm mã hoá đơn và lý do tranh chấp. Chúng tôi điều tra và điều chỉnh lỗi đã xác nhận trên hoá đơn kế tiếp hoặc bằng hoàn tiền, tuỳ trường hợp.',
          ]),
        },
      ]),
    }),
    refund: Object.freeze({
      title: 'Chính sách hoàn tiền — ecoma.io',
      heading: 'Chính sách hoàn tiền',
      description: 'Khi nào và cách ecoma.io thực hiện hoàn tiền.',
      sections: Object.freeze([
        {
          heading: 'Phạm vi',
          paragraphs: Object.freeze([
            'Chính sách này mô tả khi nào có thể yêu cầu hoàn tiền, yêu cầu được đánh giá thế nào, và khoản hoàn tiền được trả lại ra sao.',
          ]),
        },
        {
          heading: 'Điều kiện',
          paragraphs: Object.freeze([
            'Nơi luật của khu vực của bạn trao quyền rút lui hoặc hoàn tiền rộng hơn chính sách này, luật đó được áp dụng.',
            'Có thể yêu cầu hoàn tiền khi một khả năng trả phí không dùng được vì nguyên nhân từ phía ecoma.io và không được khắc phục trong thời gian hợp lý, hoặc khi hoá đơn bị lập sai.',
          ]),
        },
        {
          heading: 'Cách yêu cầu',
          paragraphs: Object.freeze([
            'Yêu cầu được gửi qua kênh hỗ trợ được công bố trên bề mặt dịch vụ, kèm mã hoá đơn hoặc mã đăng ký và mô tả vấn đề. Chúng tôi xác nhận đã nhận và phản hồi kết quả.',
          ]),
        },
        {
          heading: 'Xử lý hoàn tiền',
          paragraphs: Object.freeze([
            'Khoản hoàn tiền được duyệt sẽ được trả lại qua phương thức thanh toán ban đầu. Thời gian hiện số tiền phụ thuộc nhà cung cấp thanh toán, thường trong vài ngày làm việc.',
            'Khi chỉ một phần của kỳ đăng ký bị ảnh hưởng, khoản hoàn tiền tương ứng với phần bị ảnh hưởng; trừ khi lỗi từ phía chúng tôi, phần bị ảnh hưởng được hoàn toàn bộ.',
          ]),
        },
      ]),
    }),
  }),
});
